# Generated by Django 5.2.8 on 2025-12-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение товара",
                null=True,
                upload_to="products/",
                verbose_name="Изображение",
            ),
        ),
    ]
